services:
  eureka-server:
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    container_name: eureka-server
    ports:
      - "8761:8761"
    environment:
      - SERVER_PORT=8761
      - EUREKA_INSTANCE_HOSTNAME=eureka-server
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
    networks:
      - pasteleria-net

  gateway-service:
    build:
      context: ./gateway-service
      dockerfile: Dockerfile
    container_name: gateway-service
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - EUREKA_URL=http://eureka-server:8761/eureka/
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
    networks:
      - pasteleria-net

  ms-catalogo:
    build:
      context: ./ms-catalogo
      dockerfile: Dockerfile
    container_name: ms-catalogo
    ports:
      - "8081:8081"
    environment:
      - SERVER_PORT=8081
      - EUREKA_URL=http://eureka-server:8761/eureka/
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
    networks:
      - pasteleria-net

  ms-inventario:
    build:
      context: ./ms-inventario
      dockerfile: Dockerfile
    container_name: ms-inventario
    ports:
      - "8082:8082"
    environment:
      - SERVER_PORT=8082
      - EUREKA_URL=http://eureka-server:8761/eureka/
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
    networks:
      - pasteleria-net

  ms-venta:
    build:
      context: ./ms-venta
      dockerfile: Dockerfile
    container_name: ms-venta
    ports:
      - "8083:8083"
    environment:
      - SERVER_PORT=8083
      - EUREKA_URL=http://eureka-server:8761/eureka/
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
    networks:
      - pasteleria-net

  ms-pago:
    build:
      context: ./ms-pago
      dockerfile: Dockerfile
    container_name: ms-pago
    ports:
      - "8084:8084"
    environment:
      - SERVER_PORT=8084
      - EUREKA_URL=http://eureka-server:8761/eureka/
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
    networks:
      - pasteleria-net

  ms-compra:
    build:
      context: ./ms-compra
      dockerfile: Dockerfile
    container_name: ms-compra
    ports:
      - "8085:8085"
    environment:
      - SERVER_PORT=8085
      - EUREKA_URL=http://eureka-server:8761/eureka/
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
    networks:
      - pasteleria-net

networks:
  pasteleria-net:
    driver: bridge
